import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

//Top Bar Component
//This component needs to receive the logged in persons profile picture and name

//SideBar Component
//Needs to have a slide in and slide out
//Needs to have an enabled and disabled generate button
